name: histology_mil_nf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - glib
  - xorg-libx11
  - xorg-libxext
  - xorg-libxrender
  - xorg-libsm
  - pip:
    - git+https://github.com/digenoma-lab/HistoMILTrainer.git